# https://github.com/FilenCloudDienste/filen-rs/blob/d727995d21b6c59e15d503c390c83b9ea2c5de90/rust-toolchain.toml

[toolchain]
# we use nightly because of the `higher-ranked-assumptions` feature (https://github.com/rust-lang/rust/pull/143545)
#
# At time of writing this was causing issues with "implementation of `std::marker::Send` is not general enough"
# errors with the reworked `filen_sdk_rs::api::handle_request` function.
channel = "nightly-2026-02-20"
components = ["rust-src"]
