name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-20
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@a84bfdc502f07db5a85dd9d7a30f91a931516cc5
        with:
          shared-key: cargo-build-ci-linux-latest
          prefix-key: ''
          add-rust-environment-hash-key: 'false'
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Install Dioxus CLI
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: dioxus-cli@0.7.3
      - name: Run Dioxus build
        # this one is necessary also to generate filen-relay/assets/tailwind.css, which is otherwise missed by clippy
        run: dx build
        working-directory: filen-relay
      - name: Run clippy in filen-relay
        run: cargo clippy -- -D warnings
        working-directory: filen-relay
      - name: Run clippy in filen-relay-deployer
        run: cargo clippy -- -D warnings
        working-directory: filen-relay-deployer
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Install TOML linter
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: taplo-cli@0.10.0
      - name: Run TOML linter and formatter
        run: |
          taplo lint
          taplo fmt --check
